### ISSUE TITLE
ReCaptcha check skipped

### ISSUE THREAD

**Issue by Derbai** [thirtybees/nocaptcharecaptcha#2]
I had installed this module on TB 1.0.3 with defoult theme. The module work on backoffice but is not working on frontoffice. Expecially on Contact Us form it can be sent also without checked the reCaptcha box.

**Comment by firstred** [comment]
Are you logged in when testing? There's an option to hide and bypass the captcha when the user already has a logged in account.

**Comment by Derbai** [comment]
No, I am not logged in. http://test.italian-boutique.com/index.php?controller=contact

**Comment by firstred** [comment]
Hmmz, can't reproduce it on a vanilla instance. Do you have more details, please?

**Comment by Derbai** [comment]
I am sorry but I don't have other details. I have TB installed as test and on production and on both the reCaptcha is skipped.

**Comment by firstred** [comment]
Make sure the module's override for the contact page is active. The override is momentarily not working on that example page, but it is automatically active on a vanilla 1.0.3 store, so likely a local issue.

**Comment by Derbai** [comment]
I have manually copied module override on override folder and clear cache but still the same problem.

**Comment by slvrspiral** [comment]
I tested on a clean 1.0.4 and it worked for customer signin.

**Comment by therampagerado** [comment]
I have the same issue with my theme - warehouse. Do we need to add some settings for this module to work on other themes?

**Comment by therampagerado** [comment]
https://www.prestashop.com/forums/topic/719012-free-module-contact-form-anti-spam-recaptcha-and-blacklist-ps-151617/?_fromLogin=1

This module does work but it's only available on contact page. When I try to use contact form using the latest version of your module from here I can skip checking the captcha..
