### ISSUE TITLE
Contact form captcha verification ignored

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/nocaptcharecaptcha#5]
When 'Login attempts' settings is set to non-zero value then captcha verification on contact form is always skipped.

**Comment by BentStad** [comment]
Same problem here. When I use captcha in contact form, message is sent even if captcha is not ticked on

**Comment by Acer-ZA** [comment]
Same problem here. Even if 'Login attempts' is set to zero. 
As this bug has been reported a while back. Checked latest version of this module - and problem persists, Any update on this please?

**Comment by Acer-ZA** [comment]
There is a "fix" for this in this post here:
https://forum.thirtybees.com/topic/3477-recaptcha-not-working-at-all-ei-captcha-used-as-replacement/?do=findComment&comment=33212

Can this please be patched in the module and pushed as update for all users?

**Comment by getdatakick** [comment]
That is different issue #8
